name: Train and Push Model

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Show S3 bucket and region
        run: |
         echo s3 bucket: ${{ vars.AWS_S3_DVC_BUCKET }}
         echo region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Install dependencies
        run: |
         pip install -r requirements.txt

      - name: Configure DVC S3 remote
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          dvc remote modify s3remote access_key_id "$AWS_ACCESS_KEY_ID"
          dvc remote modify s3remote secret_access_key "$AWS_SECRET_ACCESS_KEY"

      - name: Run pipeline (generate → features → train)
        run: dvc repro

      - name: Push model to S3 for KServe
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
        run: |
          aws s3 cp models/churn_model.pkl \
            ${{ vars.AWS_S3_DVC_BUCKET }}dvc-storage-mobile-churn-model/model/churn_model.pkl

      - name: Push pipeline artifacts to DVC remote
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: dvc push
